//products actions
export const ADD_PRODUCTS="ADD_PRODUCTS";
export const PRODUCTS_LOADING="PRODUCTS_LOADING";
export const PRODUCTS_FAILED="PRODUCTS_FAILED";

//signle product actions
export const ADD_SINGLE_PRODUCT="ADD_SINGLE_PRODUCT";
export const SINGLE_PRODUCT_LOADING="SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_FAILED="SINGLE_PRODUCT_FAILED";

//cart actions
export const CART_ADD_ITEM="CART_ADD_ITEM";
export const CART_REMOVE_ITEM="CART_REMOVE_ITEM";